apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketBook
  labels:
    app: ticketBook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketBook
  template:
    metadata:
      labels:
        app: ticketBook
    spec:
      containers:
        - name: ticketBook
          image: username/ticketBook:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5